# Exploratory Data Analysis - Predict Customer Churn

## 1. Setup and data loading

In [2]:
import csv
import pandas as pd

df = pd.read_csv('train.csv')
print(f"Loaded {len(df)} rows and {len(df.columns)} columns from train.csv")

df.head()

Loaded 594194 rows and 21 columns from train.csv

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

## 2. Data Overview

## 3. Data Quality Assessment

In [3]:
null_counts = df.isnull().sum()
print("\nCounts for columns with nulls:")
print(null_counts[null_counts > 0])

Counts for columns with nulls:
Series([], dtype: int64)

In [4]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [9]:
for col in df.select_dtypes(include="object").columns:
    print(df[col].unique())
    print("\n")

/tmp/ipykernel_2307/3310466633.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

<StringArray>
['Male', 'Female']
Length: 2, dtype: str


<StringArray>
['Yes', 'No']
Length: 2, dtype: str


<StringArray>
['Yes', 'No']
Length: 2, dtype: str


<StringArray>
['Yes', 'No']
Length: 2, dtype: str


<StringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str


<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str


<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str


<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str


<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str


<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


<StringArray>
['One year', 'Two year', 'Month-to-month']
Length: 3, dtype: str


<StringArray>
['Yes', 'No']
Length: 2, dtype: str


<StringArray>
[             'Mailed check',   'Credit card (automatic)',
          'Electronic check', 'Bank transfer (automatic)']
Length: 4, dtype: str


<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Summary

- No Missing values
- No duplicates
- No incosistencies in values for object columns 
- Remove unique identifier
  * Drop id column before modelling
    df = df.drop(columns=['id'])
- Multi-Class Categories
  * on hot encoding for MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaymentMethod
    df = pd.get_dummies(df, drop_first=True)
- Binary Categories (Yes/No)
  * gender, Partner, Dependents, PhoneService, PaperlessBilling, Churn
    
- Convert target variable to binary
    

- SeniorCitizen should be a boolean
  df['SeniorCitizen'] = df['SeniorCitizen'].astype(bool)

## 4. Univariate Analysis

## 5. Bivariate Analysis